[workspace]
members = ["bins/gossip_app", "crates/gossip"]
resolver = "2"
# default-members =[]

[workspace.dependencies]
gossip = { path = "crates/gossip" }

tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}