[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

[dependencies]
utils.workspace = true
connection-manager.workspace = true
discovery.workspace = true
message.workspace = true

tracing.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true