[package]
name = "connection-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
message.workspace = true
utils.workspace = true

tracing.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true